import type { Metadata } from "next";
import { Geist, Geist_Mono, Archivo_Black } from "next/font/google";
import "./ui/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const archivo_black = Archivo_Black({
  variable: "--font-archivo_black",
  subsets: ['latin'],
  weight: '400'
})
export const metadata: Metadata = {
  title: "Lotus Glow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Lotus Glow</title>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${archivo_black.variable}`}>
        {children}
      </body>
    </html>
  );
}
